### ISSUE TITLE
Suggest removing recommendation for superfluous admin permissions

### ISSUE THREAD

**Issue by NiceneNerd** [cfw-guide/cemu.cfw.guide#4]
The only reason to grant admin permissions to Cemu is to avoid problems with people installing Cemu to a location that requires elevation. This is superfluous, and it would make more sense to recommend, for example, avoiding Program Files as an install location. Unnecessary elevation is bad practice in general, and it can cause compatibility problems with other tools (for example, BOTW users with [BOTW Editor](https://www.reddit.com/r/breathofthewow/comments/6b70uk/version_2_of_the_memory_editor/) or [BCML](https://github.com/NiceneNerd/BCML/)).

**Comment by emiyl** [comment]
Updated, thank you.
